version: '3.9'

services:
  postgres-db:
    image: postgres:14.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - test
    volumes:
      - database:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres-db
    ports:
      - 8080:8080
    networks:
      - test
    command: tail -f /dev/null

volumes:
  database:


networks:
  test:
    driver: bridge
