version: '3.9'

services:
  postgres:
    image: postgres:14.3
    environment:
      - POSTGRES_DB=faceCrawler
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - database:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.10.5
    ports:
      - 5672:5672
      - 15762:15762
    networks:
      - backend

  app:
    build: .
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 8080:8080
    networks:
      - backend
    command: tail -f /dev/null

volumes:
  database:


networks:
  backend:
    driver: bridge
